deployment:
  tasks:
    - export DEPLOYPATH=/home/dealin9/public_html/mrhsgov/
    - /bin/mkdir -p "$DEPLOYPATH"
    - /usr/bin/rsync -av --delete --exclude=".git/" --exclude=".cpanel.yml" ./ "$DEPLOYPATH"
    - /bin/date > "$DEPLOYPATH/.deploy_confirmed"