deployment:
  tasks:
    - echo "DEPLOY START" > /home/dealin9/public_html/mrhsgov/_deploy_test.txt
    - /bin/pwd >> /home/dealin9/public_html/mrhsgov/_deploy_test.txt
    - /bin/ls -la >> /home/dealin9/public_html/mrhsgov/_deploy_test.txt
    - /usr/bin/rsync -av ./ /home/dealin9/public_html/mrhsgov/